### ISSUE TITLE
Weird 20 character wrapping in `--help`

### ISSUE THREAD

**Issue by johnboiles** [nomad/shenzhen#246]
I've only seen this in the Nomad tools, all my other rubygem-based tools (Cocoapods, xcpretty) output just fine. When calling `--help` the output is wrapped to 20 characters (including the newline). Running the tool normally (`ipa build --verbose`, for example) works just fine.

```
~/Programming/iOS/Peer  (develop)> ipa build --help
  build

  Usage: ipa build
[options]

  

  Options:
    -w, --workspace
WORKSPACE Workspace
(.xcworkspace) file
to use to build app
(automatically
detected in current
directory) 
    -p, --project
PROJECT Project
(.xcodeproj) file
to use to build app
(automatically
detected in current
directory,
overridden by
--workspace option,
if passed) 
    -c,
--configuration
CONFIGURATION
Configuration used
to build 
    -s, --scheme
SCHEME  Scheme used
to build app 
    --xcconfig
XCCONFIG  use an
extra XCCONFIG file
to build the app 
    --xcargs XCARGS
pass additional
arguments to
xcodebuild when
building the app.
Be sure to quote
multiple args. 
    --[no-]clean   
Clean project
before building 
    --[no-]archive 
Archive project
after building 
    -d,
--destination
DESTINATION
Destination.
Defaults to current
directory 
    -m, --embed
PROVISION Sign .ipa
file with
.mobileprovision 
    -i, --identity
IDENTITY Identity
to be used along
with --embed 
    --sdk SDK      
use SDK as the name
or path of the base
SDK when building
the project 
    --ipa IPA      
specify the name of
the .ipa file to
generate (including
file extension) 
```

**Comment by KrauseFx** [comment]
I actually have the same issue with `fastlane` and its tools:
```
felixkrause@FelixsMBPRetina deliver (master) $ deliver --help
  deliver

  CLI for 'Deliver' - Upload screenshots, metadata and your app to the App
Store using a single command

  Commands:
    help                 Display global or [command] help documentation
    init                 Creates a new Deliverfile in the current directory
    run                  Run a deploy process using the Deliverfile in the
current folder
    testflight           Uploads a given ipa file to the new Apple
TestFlight

  Global Options:
    -f, --force          Runs a deployment without verifying any
information (PDF file). This can be used for build servers.
    --beta               Upload a beta build to iTunes Connect. This uses
the `beta_ipa` block.
    --skip-deploy        Skips submission of the build on iTunes Connect.
This will only upload the ipa and/or metadata.
    -h, --help           Display help documentation
    -v, --version        Display version information

  Author:
    Felix Krause <deliver@krausefx.com>

  Website:
    https://fastlane.tools

  GitHub:
    https://github.com/krausefx/deliver
```

just with a far more characters and only for the `--help` command. I haven't had time to look into this issue.

**Comment by johnboiles** [comment]
Thanks for the info @KrauseFx. Does it happen for everyone or just some users?

**Comment by johnboiles** [comment]
Looks like a weird interaction between [Commander](https://github.com/commander-rb/commander) and [HighLine](https://github.com/JEG2/highline)

See:
https://github.com/commander-rb/commander/issues/11
https://github.com/commander-rb/commander/issues/8

**Comment by mattt** [comment]
Fixed for 0.13.2.

**Comment by johnboiles** [comment]
@mattt: still seeing the issue on 0.13.2

```
~ > ipa --version
ipa 0.13.2
~ > ipa --help
  ipa

  Build and
distribute iOS apps
(.ipa files)

  Commands:
    build          
Create a new .ipa
file for your app
   
distribute:crashlyt
ics Distribute an
.ipa file over
Crashlytics
   
distribute:deployga
te Distribute an
.ipa file over
deploygate
    distribute:fir 
Distribute an .ipa
file over fir.im
    distribute:ftp 
Distribute an .ipa
file over FTP
   
distribute:hockeyap
p Distribute an
.ipa file over
HockeyApp
   
distribute:itunesco
nnect Upload an
.ipa file to iTunes
Connect
   
distribute:pgyer   
Distribute an .ipa
file over Pgyer
    distribute:s3  
Distribute an .ipa
file over Amazon S3
    help           
Display global or
[command] help
documentation
    info           
Show mobile
provisioning
information about
an .ipa file

  Aliases:
    distribute:sftp
distribute:ftp
--protocol sftp

  Global Options:
    --verbose      

    -h, --help     
Display help
documentation 
    -v, --version  
Display version
information 
    -t, --trace    
Display backtrace
when an error
occurs 
  
  Author:
    Mattt Thompson
<m@mattt.me>
  
  Website:
    http://mattt.me
```

**Comment by rafael** [comment]
I just updated to the latest version and start seeing this issue too.

**Comment by KrauseFx** [comment]
@mattt Unfortunately this issue isn't resolved yet. But as it seems it has nothing to do with `shenzhen` as I'm seeing the same behaviour when running [highline](https://github.com/JEG2/highline/) directly. I'll file an issue there.

**Comment by KrauseFx** [comment]
Submitted the issue with an example on how to reproduce: https://github.com/JEG2/highline/issues/138

Let's see if we get an response.

**Comment by abinoam** [comment]
Hi, It's probably a regression in HighLine.

PR at JEG2/highline#139

**Comment by abinoam** [comment]
Fix released at https://github.com/JEG2/highline/pull/139#issuecomment-94320055 
Could @johnboiles and the others please confirm is working in your setups?

**Comment by johnboiles** [comment]
That does it for me! Thanks all!

**Comment by abinoam** [comment]
Thanks @johnboiles!

**Comment by irons** [comment]
Is it expected behavior to wrap at 55 characters? That's what I'm seeing in 0.14.0, in a terminal window that's much wider.

```
$ ipa build --help 

  build

  Usage: ipa build [options]

  

  Options:
    -w, --workspace WORKSPACE Workspace (.xcworkspace)
file to use to build app (automatically detected in
current directory) 
    -p, --project PROJECT Project (.xcodeproj) file to
use to build app (automatically detected in current
directory, overridden by --workspace option, if passed) 
    -c, --configuration CONFIGURATION Configuration used
to build 
    -s, --scheme SCHEME  Scheme used to build app 
    --xcconfig XCCONFIG  use an extra XCCONFIG file to
build the app 
    --xcargs XCARGS      pass additional arguments to
xcodebuild when building the app. Be sure to quote
multiple args. 
    --[no-]clean         Clean project before building 
    --[no-]archive       Archive project after building 
    -d, --destination DESTINATION Destination. Defaults
to current directory 
    -m, --embed PROVISION Sign .ipa file with
.mobileprovision 
    -i, --identity IDENTITY Identity to be used along
with --embed 
    --sdk SDK            use SDK as the name or path of
the base SDK when building the project 
    --ipa IPA            specify the name of the .ipa
file to generate (including file extension) 
```
